export const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS';
export const FETCH_RATES_ERROR = 'FETCH_RATES_ERROR';
export const SELECT_VALUE_SAVE = 'SELECT_VALUES_SAVE';

export const VALIDATION = 'VALIDATION';
export const INPUT1_VALUE_SAVE = 'INPUT1_VALUE_SAVE';
export const INPUT2_VALUE_SAVE = 'INPUT2_VALUE_SAVE';


