export const CURRENCY = [
  {text: 'Австралийский доллар', value: 'AUD'},
  {text: 'Болгарский лев', value: 'BGN'},
  {text: 'Бразильский реал', value: 'BRL'},
  {text: 'Венгерский форинт', value: 'HUF'},
  {text: 'Гонконгский доллар', value: 'HKD'},
  {text: 'Датская крона', value: 'DKK'},
  {text: 'Доллар США', value: 'USD'},
  {text: 'Евро', value: 'EUR'},
  {text: 'Индийская рупия', value: 'INR'},
  {text: 'Индонезийская рупия', value: 'IDR'},
  {text: 'Исландская крона', value: 'ISK'},
  {text: 'Канадский доллар', value: 'CAD'},
  {text: 'Китайский юань', value: 'CNY'},
  {text: 'Корейская вона', value: 'KRW'},
  {text: 'Малайзийский ринггит', value: 'MYR'},
  {text: 'Мексиканское песо', value: 'MXN'},
  {text: 'Новозеландский доллар', value: 'NZD'},
  {text: 'Новый израильский шекель', value: 'ILS'},
  {text: 'Норвежская крона', value: 'NOK'},
  {text: 'Польский злотый', value: 'PLN'},
  {text: 'Российский рубль', value: 'RUB'},
  {text: 'Румынский лей', value: 'RON'},
  {text: 'Сингапурский доллар', value: 'SGD'},
  {text: 'Таиландский бат', value: 'THB'},
  {text: 'Турецкая лира', value: 'TRY'},
  {text: 'Филиппинское песо', value: 'PHP'},
  {text: 'Фунт стерлингов', value: 'GBP'},
  {text: 'Хорватская куна', value: 'HRK'},
  {text: 'Чешская крона', value: 'CZK'},
  {text: 'Шведская крона', value: 'SEK'},
  {text: 'Швейцарский франк', value: 'CHF'},
  {text: 'Южноафриканский рэнд', value: 'ZAR'},
  {text: 'Японская иена', value: 'JPY'},
]